import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {useState, useEffect} from "react"
import Link from "next/link"

export async  function getStaticProps(context){
  const fethPosts = await fetch("https://jsonplaceholder.typicode.com/posts")
    const data = await fethPosts.json()

  return {
    props:{data}
  }
    }
export default function Home(props) {
  const [posts, setPosts]=useState([])


console.log("Get static props data is ", props.data)
useEffect(()=>{
  
  if(props.data){
    setPosts(props.data)
  }
  
  }
  

  , [])
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     <div>Hello Next</div>
{posts.map((post)=>{
  return <div key={post.id}>
    <Link href={`posts/${post.id}`}><a><h1>{post.title}</h1></a></Link>
    <p style={{marginTop:"10px"}}>{post.body.slice(0,300)+"..."}</p>
  </div>
})}
      
    </div>
  )
}
