import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {useState, useEffect} from "react"


export async  function getServerSideProps(context){
  const fethPosts = await fetch("https://gorest.co.in/public/v2/posts")
    const data = await fethPosts.json()

  return {
    props:{data}
  }
    }
export default function Home(props) {
  const [posts, setPosts]=useState([])


console.log("data is ", props.data)
useEffect(()=>{
  
  if(props.data){
    setPosts(props.data)
  }
  
  }
  

  , [])
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     <div>Hello Next</div>
{posts.map((post)=>{
  return <div key={post.id}>
    <h1>{post.title}</h1>
    <p style={{marginTop:"10px"}}>{post.body}</p>
  </div>
})}
      
    </div>
  )
}
